version: '3.9'

services:
  backend:
    build: ./server
    ports:
      - "3001:3001"
    command: yarn devStart

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: yarn start